Updated audit log information to syslog format
sunithasomanna/ODIM pull request #105
Opened 2022-12-20 11:45 UTC by sunithasomanna

Updated audit log information to syslog format in API readme and explained each property.

2022-12-20 12:48 UTC, ashraf-vazeer approved these changes
LGTM

2022-12-20 12:54 UTC, amar-shalgar requested changes

2022-12-20 12:54 UTC, amar-shalgar commented on docs/README.md
> +<14> 1 2022-11-29T10:39:23Z odim-controller svc-systems systems-744b9475c6-bgvwm_7 GetSystemCollection [process@1 processName="systems-744b9475c6-bgvwm" transactionID="e77fe640-d8d5-4c2e-a219-31b217f
This is not audit log

2022-12-20 12:54 UTC, amar-shalgar commented on docs/README.md
> -Audit logs provide information on each API and are stored in the `api.log` file in `odimra` logs.  Each log consists of a priority value, date and time of the log, hostname from which the APIs are se
This info still holds good

2022-12-20 12:54 UTC, amar-shalgar commented on docs/README.md
> +  <110> is the value for successful operation, <107> is the value for failed operation. <14> is the value for log information.
110 and 107 are for audit logs success and error logs. there is a big list of priority values , pls add all

2022-12-21 08:30 UTC, sunithasomanna commented on docs/README.md
> +<14> 1 2022-11-29T10:39:23Z odim-controller svc-systems systems-744b9475c6-bgvwm_7 GetSystemCollection [process@1 processName="systems-744b9475c6-bgvwm" transactionID="e77fe640-d8d5-4c2e-a219-31b217f
fixed

2022-12-21 08:30 UTC, sunithasomanna commented on docs/README.md
> +<14> 1 2022-11-29T10:39:23Z odim-controller svc-systems systems-744b9475c6-bgvwm_7 GetSystemCollection [process@1 processName="systems-744b9475c6-bgvwm" transactionID="e77fe640-d8d5-4c2e-a219-31b217f
retained the existing content of audit log

2022-12-21 08:31 UTC, sunithasomanna commented on docs/README.md
> +  <110> is the value for successful operation, <107> is the value for failed operation. <14> is the value for log information.
referred users to priority values in Log levels section in Getting Started Readme

2022-12-21 08:31 UTC, sunithasomanna commented on docs/README.md
> -Audit logs provide information on each API and are stored in the `api.log` file in `odimra` logs.  Each log consists of a priority value, date and time of the log, hostname from which the APIs are se
retained the existing content of audit log

2022-12-21 11:16 UTC, amar-shalgar approved these changes

2022-12-21 11:17 UTC, merged