Consistency in the API readme
sunithasomanna/ODIM pull request #126
Opened 2023-05-19 11:07 UTC by sunithasomanna

Fixed all consistency issues in the API readme; mostly the ones with 202 Accepted and its following status codes.

2023-05-19 16:08 UTC, mohamed-shahid-afrid approved these changes

2023-05-22 07:58 UTC, amar-shalgar requested changes

2023-05-22 07:58 UTC, amar-shalgar commented on docs/README.md
> +|/redfish/v1/Managers/{ManagerId}/VirtualMedia/{VirtualMediaId}| `GET`  |
EthernetInterface is given as Id however here it is VirtualMediaId, please check for consistency

2023-05-22 15:53 UTC, sunithasomanna commented on docs/README.md
> +|/redfish/v1/Managers/{ManagerId}/VirtualMedia/{VirtualMediaId}| `GET`  |
Fixed. However, {ids} are variables and in general, they can be represented in any form. These are very minor things which will go away once the automation process is rolled out. Also, the existing string doesn't convey incorrect information or doesn't affect the overall quality of documentation.

2023-05-23 08:59 UTC, amar-shalgar approved these changes

2023-05-23 08:59 UTC, merged