Replace colons with a period
sunithasomanna/ODIM pull request #18
Opened 2021-11-22 07:08 UTC by sunithasomanna

Replacing colons with period for relevant parameters in the API readme.
Also removed extra spaces before the headings

2021-11-30 06:40 UTC, rohitkumar-ro approved these changes
Changes looks fine

2021-11-30 06:55 UTC, arahimanshaik approved these changes
Looks good for me

2021-11-30 07:03 UTC, hemkapoor approved these changes

2021-11-30 11:46 UTC, jeevan-kamkar approved these changes

2021-11-30 21:02 UTC, Bharath-KKB commented on docs/README.md
> +  - Plugin for unmanaged racks (URP): Plugin that acts as a resource manager for unmanaged racks.
We are missing Cisco ACI, Lenovo and Dell plugins?

2021-11-30 21:04 UTC, Bharath-KKB commented on docs/README.md
> +This guide provides reference information for the northbound APIs exposed by the resource aggregator. These APIs are designed as per DMTF's [Redfish® Scalable Platforms API (Redfish) specification 1.
Confirm if this is the right version

2021-11-30 21:07 UTC, Bharath-KKB commented on docs/README.md
>  The services layer is where all the services are hosted. This layer implements service logic for all use cases
This is wrong. Services and collections both provide functionality. Also the figure is that of collections... no services there

2021-11-30 21:08 UTC, Bharath-KKB commented on docs/README.md
> +responses coming from the plugin layer are mapped to the actual end resources in this layer. It maintains the state for event subscriptions, credentials, and tasks. It also hosts a message bus called
What is a PMB?

2021-11-30 21:09 UTC, Bharath-KKB commented on docs/README.md
> +responses coming from the plugin layer are mapped to the actual end resources in this layer. It maintains the state for event subscriptions, credentials, and tasks. It also hosts a message bus called
Plus _" Requests coming from the API layer and the responses coming from the plugin layer are mapped to the actual end resources in this layer."_ is not correct.

2021-11-30 21:12 UTC, Bharath-KKB commented on docs/README.md
> +responses coming from the plugin layer are mapped to the actual end resources in this layer. It maintains the state for event subscriptions, credentials, and tasks. It also hosts a message bus called
This _"This layer hosts a message broker which acts as a communication channel between the upper layers and the plugin layer. It supports common messaging architecture and real-time streaming. Resource Aggregator for ODIM uses Kafka as the event message bus. The services and the event message bus layers host Redis data store."_ needs changes. This is only used for events. And arent we supporting redis streams ?

2021-11-30 21:14 UTC, Bharath-KKB commented on docs/README.md
> +This layer connects the actual managed resources to the aggregator layers and is de-coupled from the upper layers. A plugin abstracts vendor-specific access protocols to a common interface which the
We cannot claim OpenAPI v3 support. Also _"The messaging mechanism is based on OpenMessaging Specification."_ doesnt look right

2021-11-30 21:15 UTC, Bharath-KKB requested changes
Pls fix the issues identified.

2021-12-07 11:05 UTC, sunithasomanna commented on docs/README.md
> +  - Plugin for unmanaged racks (URP): Plugin that acts as a resource manager for unmanaged racks.
Addressed all your comments on a different PR (https://github.com/sunithasomanna/ODIM/pull/21). Please review the updated document at https://github.com/sunithasomanna/ODIM/blob/sprint-47-odim-68/docs/README.md

2021-12-07 13:21 UTC, Bharath-KKB approved these changes

2021-12-07 13:23 UTC, shivacharanms approved these changes

2021-12-13 06:40 UTC, sunithasomanna commented
Addressed all comments given by Bharath K, on a different PR (#21). Please review the updated document at https://github.com/sunithasomanna/ODIM/blob/sprint-47-odim-68/docs/README.md

2021-12-13 09:32 UTC, merged