Redis Stream support as EMB
sunithasomanna/ODIM pull request #20
Opened 2021-11-29 09:40 UTC by sunithasomanna

Adding information in the API readme that ODIM uses Redis Stream as the Event Message Bus (EMB), along with Kafka.

2021-11-30 06:48 UTC, rohitkumar-ro approved these changes

2021-11-30 07:03 UTC, hemkapoor approved these changes

2021-11-30 07:04 UTC, arahimanshaik approved these changes

2021-11-30 11:46 UTC, jeevan-kamkar approved these changes

2021-11-30 11:47 UTC, irappa-pattar approved these changes

2021-11-30 20:56 UTC, Bharath-KKB commented on docs/README.md
> +ODIM uses Kafka and Redis Stream as the event message bus.
Are we saying both are supported simultaneously ?

2021-11-30 20:57 UTC, Bharath-KKB requested changes
disambiguate the changed line. Also is the code checked in ?

2021-12-02 12:16 UTC, sunithasomanna commented
Closing this PR. Addition of Redis stream info is covered in another PR (because it's a part of ODIM architecture section).
https://github.com/sunithasomanna/ODIM/pull/21

2021-12-02 12:16 UTC, closed without merging