New section - Message bus configuration
sunithasomanna/ODIM pull request #22
Opened 2021-12-09 07:14 UTC by sunithasomanna

Added instructions for configuring message bus (in Plugin Developer's Guide).
Added description for the configuration parameters.

2021-12-09 07:57 UTC, Bharath-KKB commented on plugin-redfish/README.md
> +"HASet": "redisSentinel",
We should not have parameters specific to a message bus type in this config. MessagebusAddress/MessagePort/HASet should be removed and be part of the messagebus configfilepath

2021-12-09 07:58 UTC, Bharath-KKB commented on plugin-redfish/README.md
> +"MessageQueueConfigFilePath": "",
MessageQueueConfigFilePath should be changed to Message**Bus**ConfigFilePath. Get the team to fix this before the docs are set right

2021-12-09 07:58 UTC, Bharath-KKB requested changes
Address the two comments.

2021-12-23 09:10 UTC, sunithasomanna commented on plugin-redfish/README.md
> +"HASet": "redisSentinel",
Fixed in doc.

2021-12-23 09:12 UTC, sunithasomanna commented on plugin-redfish/README.md
> +"MessageQueueConfigFilePath": "",
Informed Jeevan. Will be fixing it in Jan. Once that is fixed, I'll update the document. Keeping this PR open until then!

2022-01-12 07:51 UTC, sunithasomanna commented on plugin-redfish/README.md
> +"MessageQueueConfigFilePath": "",
Updated the parameter name `MessageQueueConfigFilePath` with `MessageBusConfigFilePath` after Dev update.

2022-01-13 09:41 UTC, Bharath-KKB approved these changes

2022-01-13 14:32 UTC, shivacharanms approved these changes

2022-01-13 14:32 UTC, merged