Audit logging
sunithasomanna/ODIM pull request #27
Opened 2022-01-17 12:31 UTC by sunithasomanna

Added a new section "Audit logging" in the API readme.

2022-01-18 05:54 UTC, shivacharanms approved these changes

2022-01-24 08:50 UTC, shivacharanms approved these changes

2022-01-24 09:35 UTC, jeevan-kamkar approved these changes

2022-01-24 10:24 UTC, amar-shalgar requested changes
Please address the changes

2022-01-24 10:24 UTC, amar-shalgar commented on docs/README.md
> +Audit logs has information on each API and is stored in the API.log file.  Each log consists of a code number followed by the date and time of the log, hostname from which the APIs were sent, user ac
API.log should be api.log under odimra logs

2022-01-24 10:24 UTC, amar-shalgar commented on docs/README.md
> +  <blockquote> Note: <110> is the audit information code and <107> is the audit error code. </blockquote>
<110> and <107> are the Priority value 110 indicates audit info log and 107 indicates audit error log

2022-01-24 10:27 UTC, Bharath-KKB requested changes
Do not merge into dev branch till we get approval for this.

2022-01-31 05:14 UTC, sunithasomanna commented on docs/README.md
> +  <blockquote> Note: <110> is the audit information code and <107> is the audit error code. </blockquote>
done

2022-01-31 05:14 UTC, sunithasomanna commented on docs/README.md
> +Audit logs has information on each API and is stored in the API.log file.  Each log consists of a code number followed by the date and time of the log, hostname from which the APIs were sent, user ac
done

2022-02-01 09:36 UTC, shivacharanms commented on docs/README.md
> +- <110> 2009-11-10T23:00:00Z 10.24.1.237 [account@1 user="admin" roleID="Administrator"][request@1 method="GET" resource="/redfish/v1/Systems" requestBody=""][response@1 responseCode=200] Operation S
Change the IPs everywhere to opensource IPs, eg: 192.168.100.101

2022-02-01 10:07 UTC, shivacharanms commented on docs/README.md
> +- <110> 2009-11-10T23:00:00Z 10.24.1.237 [account@1 user="admin" roleID="Administrator"][request@1 method="GET" resource="/redfish/v1/Systems" requestBody=""][response@1 responseCode=200] Operation S
Take this up as a separate change in a new PR with IP changes across all references

2022-02-01 10:08 UTC, amar-shalgar approved these changes

2022-02-01 10:09 UTC, merged