Update all third-party component versions and related screens - New PR
sunithasomanna/ODIM pull request #28
Opened 2022-01-27 07:29 UTC by sunithasomanna

Closed the old PR related to these changes because of additional feedback from the QA team and moving it to this sprint.

- Update the versions of the following components in the Getting Started Readme
   Kubespray
   etcd
   docker
   K8S
   Ubuntu 
   Redfish Schema and Spec
   kube-master 
   kube-node 
   Helm charts 
   Keepalived
   Stakater/Reloader 
   linux-headers
   docker image versions of K8S and ODIMRA services
- Renamed the following:
   kube-master - kube_control_plane
   kube-node - kube_node
- Updated screenshots of the sample output pods and services. 
- Updated team's additional feedback from Dev and QA teams

2022-02-01 09:24 UTC, irappa-pattar approved these changes

2022-02-01 09:31 UTC, jeevan-kamkar approved these changes

2022-02-01 09:48 UTC, shivacharanms reviewed
K8s docker images and odimra images screenshots to be updated

2022-02-03 17:07 UTC, sunithasomanna commented
> K8s docker images and odimra images screenshots to be updated

Done!

2022-02-07 13:35 UTC, sukhwinder20 commented on README.md
> +   |calico/node|v3.15.1 |calico/node.tar |
Old kubernetes images needs to be removed

2022-02-07 13:37 UTC, sukhwinder20 commented on README.md
> +     docker save urplugin:1.0 -o ~/plugins/urplugin/urplugin.tar
urplugin version is 3.0 in above docker image list

2022-02-07 13:38 UTC, sukhwinder20 commented on README.md
> +    docker save grfplugin:1.0 -o ~/plugins/grfplugin/grfplugin.tar
grfplugin version is 3.0

2022-02-09 06:31 UTC, sunithasomanna commented on README.md
> +   |calico/node|v3.15.1 |calico/node.tar |
removed

2022-02-09 06:31 UTC, sunithasomanna commented on README.md
> +     docker save urplugin:1.0 -o ~/plugins/urplugin/urplugin.tar
done

2022-02-09 06:31 UTC, sunithasomanna commented on README.md
> +    docker save grfplugin:1.0 -o ~/plugins/grfplugin/grfplugin.tar
done

2022-02-09 10:50 UTC, sukhwinder20 commented on README.md
> +   |k8s.gcr.io/k8s-dns-node-cache| 1.15.13 |k8s.gcr.io/k8s-dns-node-cache.tar |
this is old image (k8s.gcr.io/k8s-dns-node-cache| 1.15.13 |k8s.gcr.io/k8s-dns-node-cache.tar) |

2022-02-09 10:50 UTC, sukhwinder20 requested changes
Remove old kubernetes image

2022-02-09 10:56 UTC, sunithasomanna commented on README.md
> +   |k8s.gcr.io/k8s-dns-node-cache| 1.15.13 |k8s.gcr.io/k8s-dns-node-cache.tar |
done

2022-02-09 12:16 UTC, rohitkumar-ro approved these changes

2022-02-09 12:17 UTC, rohitkumar-ro approved these changes

2022-02-10 09:24 UTC, amar-shalgar approved these changes

2022-02-10 09:39 UTC, sukhwinder20 commented on README.md
> +    Example: `docker save -o api.tar api:2.0`
api version is 3

2022-02-10 09:39 UTC, sukhwinder20 requested changes
Api version is 3.0

2022-02-10 09:44 UTC, sunithasomanna commented on README.md
> +    Example: `docker save -o api.tar api:2.0`
done

2022-02-10 09:50 UTC, sukhwinder20 approved these changes

2022-02-10 10:03 UTC, shivacharanms approved these changes

2022-02-10 10:18 UTC, merged