Documented Support for URL Encoding
sunithasomanna/ODIM pull request #3
Opened 2021-06-20 15:34 UTC by sunithasomanna

Updated Support for URL Encoding information in API readme

2021-06-21 04:01 UTC, Bharath-KKB requested changes
As discussed add all the special characters being escaped and their encoded representation.

2021-06-28 05:50 UTC, sunithasomanna commented
> As discussed add all the special characters being escaped and their encoded representation.

Updated information saying all characters are supported and referred users to the following hyperlink of URL Encoding Reference (standard site), as discussed in the scrum meeting last week. 
https://www.w3schools.com/tags/ref_urlencode.ASP

2021-07-07 08:25 UTC, bharath-b-hpe approved these changes

2021-07-20 05:24 UTC, amar-shalgar approved these changes
LGTM

2021-07-20 05:29 UTC, merged