Add EMB paramters details in kube_deploy_nodes.yaml file
sunithasomanna/ODIM pull request #30
Opened 2022-01-31 06:25 UTC by sunithasomanna

In the Getting Started Readme, added new EMB parameters in kube yaml file and their descriptions in the odim-controller config paramters table

2022-01-31 10:10 UTC, shivacharanms approved these changes

2022-01-31 10:11 UTC, shivacharanms requested changes

2022-01-31 10:11 UTC, shivacharanms commented on README.md
> +|MessageBusType|Event message bus type. It is either Kafka or RedisStream.|
Please add a condition in brackets 'These values are type sensitive and should be as given'

2022-01-31 11:37 UTC, sunithasomanna commented on README.md
> +|MessageBusType|Event message bus type. It is either Kafka or RedisStream.|
done

2022-01-31 11:41 UTC, shivacharanms approved these changes

2022-02-01 08:37 UTC, arahimanshaik approved these changes

2022-02-01 09:22 UTC, irappa-pattar approved these changes

2022-02-01 09:32 UTC, jeevan-kamkar approved these changes

2022-02-01 10:00 UTC, shivacharanms commented on README.md
> +|MessageBusQueue|Event message bus queue name.|
The value should not have spaces.

2022-02-01 10:26 UTC, irappa-pattar commented on README.md
> +|MessageBusQueue|Event message bus queue name.|
Allowed characters for topic creations are alphabets, numbers, period, underscore, and hyphen.

2022-02-01 10:40 UTC, shivacharanms approved these changes

2022-02-01 11:34 UTC, merged