Added Lenovo plugin deployment instructions
sunithasomanna/ODIM pull request #31
Opened 2022-01-31 06:51 UTC by sunithasomanna

Added Lenovo plugin deployment instructions to Getting Started readme

2022-01-31 10:48 UTC, shivacharanms approved these changes

2022-02-01 09:21 UTC, irappa-pattar approved these changes

2022-02-01 09:33 UTC, jeevan-kamkar approved these changes

2022-02-02 05:56 UTC, sukhwinder20 commented on README.md
> +
add cd ODIM

2022-02-03 03:43 UTC, sunithasomanna commented on README.md
> +
done

2022-02-07 11:46 UTC, sukhwinder20 commented on README.md
> +18. [Add the Lenovo plugin into the Resource Aggregator for ODIM framework](#adding-a-plugin-into-the-resource-aggregator-for-odim-framework).
Add the example in section Add the Lenovo plugin into the Resource Aggregator for ODIM framework

2022-02-07 11:46 UTC, sukhwinder20 requested changes
Lenovoplugin ports information is required to be added

2022-02-07 11:49 UTC, sunithasomanna commented on README.md
> +18. [Add the Lenovo plugin into the Resource Aggregator for ODIM framework](#adding-a-plugin-into-the-resource-aggregator-for-odim-framework).
Done

2022-02-07 11:50 UTC, sunithasomanna commented
> Lenovoplugin ports information is required to be added

Done

2022-02-07 13:33 UTC, sukhwinder20 approved these changes

2022-02-09 06:52 UTC, merged