Add instructions for URP, GRF and Dell plugins deployment
sunithasomanna/ODIM pull request #4
Opened 2021-06-22 12:14 UTC by sunithasomanna

Adding instructions for URP, GRF and Dell plugins deployment + their addition to ODIM. 
Instructions are documented in the main readme, and the relevant plugin instructions are linked from the main readme to the readme present in the respective plugin dirs.

2021-06-24 06:50 UTC, bharath-b-hpe commented on README.md
> +<<<<<<< Updated upstream
Please resolve the conflicts indicated by git

2021-06-24 06:56 UTC, bharath-b-hpe requested changes
Please sync the branch with upstream development, PR contains other changes too.

2021-06-24 11:49 UTC, sunithasomanna commented on README.md
> +<<<<<<< Updated upstream
Done! Resolved conflicts! Please verify

2021-06-29 18:47 UTC, sukhwinder20 commented on plugin-dell/README.md
>  ## API accessibility
This is not required in Dell plugin

2021-07-02 09:45 UTC, sunithasomanna commented
Changing Title to include Kubernetes deployment of ODIMRA

2021-07-21 08:05 UTC, sunithasomanna commented
Closing this PR because it is no longer valid. Had files other than the ones relevant to documentation. Raised a new PR for this and got the content approved and merged to upstream dev branch. Hence closing this PR.

2021-07-21 08:05 UTC, closed without merging