Update ConnectionMethodVariant versions for all plugins
sunithasomanna/ODIM pull request #40
Opened 2022-02-15 06:02 UTC by sunithasomanna

Update ConnectionMethodVariant versions for all plugins in Getting Started Readme.

2022-02-15 06:55 UTC, jeevan-kamkar requested changes
Address the requested chages

2022-02-15 06:55 UTC, jeevan-kamkar commented on README.md
> +        3connectionMethodConf:
it should be connectionMethodConf not 3connectionMethodConf update the same

2022-02-15 06:59 UTC, sunithasomanna commented on README.md
> +        3connectionMethodConf:
fixed

2022-02-15 07:58 UTC, jeevan-kamkar approved these changes

2022-02-22 04:32 UTC, sunithasomanna commented
Closing this PR because it will not be taken for the phase 4. Retaining the existing versions for ConnectionMethodVariant parameter for all plugins.

2022-02-22 04:32 UTC, closed without merging