Update Scaling up and scaling down resources section
sunithasomanna/ODIM pull request #42
Opened 2022-02-15 12:22 UTC by sunithasomanna

Update Scaling up and scaling down resources section as per Ashraf feedback in Getting Started readme.

2022-02-16 06:25 UTC, jeevan-kamkar requested changes
address the requested changes

2022-02-16 06:25 UTC, jeevan-kamkar commented on README.md
> +| update                   | Name of the update service                                   |
telemetry service name is missing in the list please add the same

2022-02-16 07:58 UTC, sunithasomanna commented on README.md
> +| update                   | Name of the update service                                   |
added

2022-02-16 11:10 UTC, jeevan-kamkar approved these changes

2022-02-18 08:37 UTC, irappa-pattar approved these changes

2022-02-22 06:16 UTC, amar-shalgar approved these changes

2022-02-22 09:39 UTC, shivacharanms approved these changes

2022-02-22 09:39 UTC, merged