Added Remote BMC accounts and roles
sunithasomanna/ODIM pull request #53
Opened 2022-05-04 08:50 UTC by sunithasomanna

- Added a new section "Remote BMC accounts and roles" in the API readme.
- Changed the heading level for 2 VirtualMedia topics.

2022-05-09 13:11 UTC, amar-shalgar requested changes

2022-05-09 13:11 UTC, amar-shalgar commented on docs/README.md
> +"Password": "HP1nvent1"
Please add a standard password across requests

2022-05-10 06:41 UTC, sunithasomanna commented on docs/README.md
> +"Password": "HP1nvent1"
Addressed

2022-05-17 05:41 UTC, amar-shalgar requested changes

2022-05-17 05:41 UTC, amar-shalgar commented on docs/README.md
> +<blockquote> NOTE: Before accessing these endpoints, ensure that the user has the required privileges. If you access these endpoints without necessary privileges, you will receive an HTTP `403 Forbid
This sentence should be - "you will receive a HTTP" instead of "you will receive an HTTP"

2022-05-17 06:19 UTC, amar-shalgar approved these changes

2022-05-17 06:27 UTC, sunithasomanna commented on docs/README.md
> +<blockquote> NOTE: Before accessing these endpoints, ensure that the user has the required privileges. If you access these endpoints without necessary privileges, you will receive an HTTP `403 Forbid
Explained rules of articles usage

2022-05-17 11:48 UTC, shivacharanms approved these changes

2022-05-17 11:48 UTC, merged