Added LicenseService APIs
sunithasomanna/ODIM pull request #59
Opened 2022-05-16 06:03 UTC by sunithasomanna

Added LicenseService APIs in the API readme

2022-05-17 05:31 UTC, amar-shalgar requested changes
Please address changes

2022-05-17 05:31 UTC, amar-shalgar commented on docs/README.md
> + 'https://{odimra_host}:{port}/redfish/v1/LinceseService'
Please correct the spelling for LinceseService

2022-05-17 05:31 UTC, amar-shalgar commented on docs/README.md
> +   "Id":"",
ID cannot be empty

2022-05-17 05:31 UTC, amar-shalgar commented on docs/README.md
> + 'https://{odimra_host}:{port}/redfish/v1/LinceseService/Licenses/'
Please check the spelling

2022-05-17 05:31 UTC, amar-shalgar commented on docs/README.md
> +   "LicenseType":"Perpetual"
This response looks incomplete

2022-05-17 11:45 UTC, sunithasomanna commented on docs/README.md
> + 'https://{odimra_host}:{port}/redfish/v1/LinceseService'
done

2022-05-17 11:45 UTC, sunithasomanna commented on docs/README.md
> +   "Id":"",
done

2022-05-18 08:09 UTC, hemkapoor approved these changes
LGTM

2022-05-18 08:19 UTC, jeevan-kamkar approved these changes

2022-05-18 11:45 UTC, amar-shalgar approved these changes

2022-05-18 11:48 UTC, shivacharanms approved these changes

2022-05-18 11:48 UTC, merged