Add VirtualMedia Information in the API Readme
sunithasomanna/ODIM pull request #6
Opened 2021-06-28 08:44 UTC by sunithasomanna

Add detailed information on the following VirtualMedia APIs in the API readme:

/redfish/v1/Managers/{ManagerId}/VirtualMedia
/redfish/v1/Managers/{ManagerId}/VirtualMedia/{VirtualMediaID}
/redfish/v1/Managers/{ManagerId}/VirtualMedia/{VirtualMediaID}/Actions/VirtualMedia.InsertMedia
/redfish/v1/Managers/{ManagerId}/VirtualMedia/{VirtualMediaID}/Actions/VirtualMedia.EjectMedia

2021-07-07 08:24 UTC, bharath-b-hpe approved these changes

2021-07-20 05:16 UTC, amar-shalgar requested changes
Please address comments

2021-07-20 05:16 UTC, amar-shalgar commented on docs/README.md
> +{
Response body is incorrect. Please correct it

2021-07-20 05:16 UTC, amar-shalgar commented on docs/README.md
> +{
This response got changed, Please update

2021-07-20 05:16 UTC, amar-shalgar commented on docs/README.md
> +{
This response got changed, pls update

2021-07-20 10:52 UTC, sunithasomanna commented on docs/README.md
> +{
addressed

2021-07-20 10:52 UTC, sunithasomanna commented on docs/README.md
> +{
addressed

2021-07-20 10:52 UTC, sunithasomanna commented on docs/README.md
> +{
addressed

2021-07-20 11:27 UTC, amar-shalgar approved these changes
Virtual media details looks OK

2021-07-20 12:05 UTC, merged