Add server instructions with IPv6 address information
sunithasomanna/ODIM pull request #60
Opened 2022-05-17 12:53 UTC by sunithasomanna

- Add BMC server (with IPv6 address and update the section accordingly with sample request, response and parameters description in the API readme.
- Updated IPv4 hostname with public IP.

2022-05-18 08:09 UTC, amar-shalgar requested changes

2022-05-18 08:09 UTC, amar-shalgar commented on docs/README.md
> +   "HostName":"192.168.256.256",
255 is the maximum allowed number. Please change this

2022-05-18 08:09 UTC, amar-shalgar commented on docs/README.md
> +   "HostName":"192.168.256.256",
Add a valid IP address

2022-05-23 10:15 UTC, sunithasomanna commented on docs/README.md
> +   "HostName":"192.168.256.256",
done

2022-05-23 10:15 UTC, sunithasomanna commented on docs/README.md
> +   "HostName":"192.168.256.256",
done

2022-05-23 10:40 UTC, jeevan-kamkar approved these changes

2022-05-23 11:23 UTC, amar-shalgar approved these changes

2022-05-23 17:00 UTC, shivacharanms approved these changes

2022-05-23 17:00 UTC, merged