Add POST method for LicenseService
sunithasomanna/ODIM pull request #68
Opened 2022-06-07 11:17 UTC by sunithasomanna

Added instructions for POST method for LicenseService in API readme

2022-06-10 07:28 UTC, amar-shalgar requested changes

2022-06-10 07:28 UTC, amar-shalgar commented on docs/README.md
> +| /redfish/v1/LicenseService/Licenses/            | GET, POST            | `Login`, `ConfigureSelf` |
Privilege is incorrect. Update the correct one

2022-06-10 07:28 UTC, amar-shalgar commented on docs/README.md
> +| **Returns**        | License string installed on the authorized BMC server(s). |
It should not return license string

2022-06-10 07:28 UTC, amar-shalgar commented on docs/README.md
> +  "LicenseString": "333K2-8QLV4-Y8R3G-LJQQX-7BK6M",
Give a dummy string

2022-06-10 07:28 UTC, amar-shalgar commented on docs/README.md
> +  "LicenseString": "333K2-8QLV4-Y8R3G-LJQQX-7BK6M",
Give a dummy string

2022-06-13 06:06 UTC, sunithasomanna commented on docs/README.md
> +| /redfish/v1/LicenseService/Licenses/            | GET, POST            | `Login`, `ConfigureSelf` |
Updated with `ConfigureManager`. Thanks for the catch

2022-06-13 06:16 UTC, sunithasomanna commented on docs/README.md
> +| **Returns**        | License string installed on the authorized BMC server(s). |
addressed comment

2022-06-13 06:17 UTC, sunithasomanna commented on docs/README.md
> +  "LicenseString": "333K2-8QLV4-Y8R3G-LJQQX-7BK6M",
done

2022-06-13 06:18 UTC, sunithasomanna commented on docs/README.md
> +  "LicenseString": "333K2-8QLV4-Y8R3G-LJQQX-7BK6M",
done

2022-06-13 06:27 UTC, hemkapoor approved these changes

2022-06-13 11:03 UTC, amar-shalgar approved these changes

2022-06-13 11:57 UTC, shivacharanms approved these changes

2022-06-13 11:58 UTC, merged