Using protoc compiler instructions
sunithasomanna/ODIM pull request #74
Opened 2022-06-14 09:24 UTC by sunithasomanna

Added "Using protoc compiler" instructions in the Getting Started readme.

2022-06-15 10:27 UTC, jeevan-kamkar approved these changes

2022-06-15 13:09 UTC, chauberahul1993 approved these changes

2022-06-15 15:25 UTC, amar-shalgar approved these changes

2022-06-16 11:07 UTC, shivacharanms requested changes

2022-06-16 11:07 UTC, shivacharanms commented on README.md
> +   wget https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protoc-3.19.1-linux-x86_64.zip.
Remove the period at the end

2022-06-16 11:07 UTC, shivacharanms commented on README.md
> +   wget https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protoc-3.19.1-linux-x86_64.zip.
Change the command to 'wget https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protoc-3.19.1-linux-x86_64.zip -P /tmp/'

2022-06-16 11:07 UTC, shivacharanms commented on README.md
> +   2. Create a directory `proto_files`:
Remove step

2022-06-16 11:07 UTC, shivacharanms commented on README.md
> +      protoc-3.19.1-linux-x86_64.zip -d proto_files`
Update command to 'unzip /tmp/protoc-3.19.1-linux-x86_64.zip -d proto_files'

2022-06-16 12:29 UTC, sunithasomanna commented on README.md
> +   wget https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protoc-3.19.1-linux-x86_64.zip.
done

2022-06-16 12:30 UTC, sunithasomanna commented on README.md
> +      protoc-3.19.1-linux-x86_64.zip -d proto_files`
done

2022-06-16 12:30 UTC, sunithasomanna commented on README.md
> +   2. Create a directory `proto_files`:
done

2022-06-16 13:06 UTC, shivacharanms approved these changes

2022-06-16 14:16 UTC, merged