Undelivered (persist) events
sunithasomanna/ODIM pull request #78
Opened 2022-06-30 05:40 UTC by sunithasomanna

Added info for undelivered events in API readme

2022-06-30 11:36 UTC, jeevan-kamkar approved these changes

2022-06-30 11:57 UTC, lpooja approved these changes

2022-07-04 07:14 UTC, amar-shalgar requested changes

2022-07-04 07:14 UTC, amar-shalgar commented on docs/README.md
> +After subscribing to Resource Aggregator for ODIM events, you receive them regularly on your system. In instances where your system is unavailable to listen to the events for a certain period, the ev
let us generalize the no. of times and seconds.

2022-07-05 08:45 UTC, chauberahul1993 approved these changes

2022-07-05 09:08 UTC, sunithasomanna commented on docs/README.md
> +After subscribing to Resource Aggregator for ODIM events, you receive them regularly on your system. In instances where your system is unavailable to listen to the events for a certain period, the ev
done

2022-07-05 10:32 UTC, amar-shalgar approved these changes

2022-07-05 10:48 UTC, merged