Update Telemetry Services Instructions in API Guide
sunithasomanna/ODIM pull request #8
Opened 2021-07-08 11:00 UTC by sunithasomanna

Updated Telemetry Services Instructions in API Readme with the following API URIs and their details:

/redfish/v1/TelemetryService
/redfish/v1/TelemetryService/MetricDefinitions
/redfish/v1/TelemetryService/MetricDefinitions/{MetricDefinitionID}
/redfish/v1//TelemetryService/MetricReportDefinitions
/redfish/v1/TelemetryService/MetricReportDefinitions/{MetricReportDefinitionID}
/redfish/v1/TelemetryService/MetricReports
/redfish/v1/TelemetryService/MetricReports/{MetricReportID}
/redfish/v1/TelemetryService/Triggers
/redfish/v1/TelemetryService/Triggers/{TriggerID}

2021-07-08 11:48 UTC, shivacharanms requested changes

2021-07-08 11:48 UTC, shivacharanms commented on docs/README.md
> +| /redfish/v1//TelemetryService/MetricReportDefinitions        | `GET`,         |
"," to be removed

2021-07-08 11:48 UTC, shivacharanms commented on docs/README.md
> +   "Tasks": {
Should be TelemetryService

2021-07-08 11:48 UTC, shivacharanms commented on docs/README.md
> + 'https://{odimra_host}:{port}/redfish/v1/Fabrics/{fabricID}/AddressPools/{addresspo'
Fix on format

2021-07-08 11:48 UTC, shivacharanms commented on docs/README.md
> +| /redfish/v1/TelemetryService/MetricDefinitions/{MetricDefinitionID} | GET                  | `Login`                 |
Indent format fix

2021-07-08 11:48 UTC, shivacharanms commented on docs/README.md
> +   "@odata.id":"/redfish/v1/TelemetryService/MetricDefinitions/PowerConsumedWatts",
Sample response to collection should be a collection, not individual resource info

2021-07-08 11:48 UTC, shivacharanms commented on docs/README.md
> +{
Response to collection should be collection of members

2021-07-08 11:48 UTC, shivacharanms commented on docs/README.md
> +   "@odata.id":"/redfish/v1/TelemetryService/Triggers/PlatformPowerCapTriggers",
Response to collection should be collection of members

2021-07-08 11:48 UTC, shivacharanms commented on docs/README.md
> + 'https://10.24.1.33:30080/redfish/v1/TelemetryService/Triggers/{TriggersID}'
Remove IP address

2021-07-11 14:27 UTC, sunithasomanna commented on docs/README.md
> +   "Tasks": {
"TelemetryService" is also added below just below "TaskService". Please verify.

2021-07-13 14:58 UTC, shivacharanms requested changes
Please change the heading of this section from "Redfish Telemetry" to "Telemetry"

2021-07-13 14:58 UTC, shivacharanms commented on docs/README.md
> +| **Description**    | This operation lists the metadata information for the metrics collection. |
change metrics to metric definitions

2021-07-13 14:58 UTC, shivacharanms commented on docs/README.md
> +| **Description**    | This operation lists the metadata information for a metric.  |
change metric to metric definition

2021-07-13 14:58 UTC, shivacharanms commented on docs/README.md
> +| **Returns**        | JSON schema defining the content of the multiple metric report |
change multiple to collection and metric report to metric report definition

2021-07-13 14:58 UTC, shivacharanms commented on docs/README.md
> +| **Returns**        | JSON schema defining the content of the single metric report |
change metric report to metric report definition

2021-07-15 11:33 UTC, irappa-pattar requested changes

2021-07-15 11:33 UTC, irappa-pattar commented on docs/README.md
> +              'https://{odimra_host}:{port}/redfish/v1/TelemetryService/MetricDefinitions/'
please remove trailing slash in the URI

2021-07-15 11:33 UTC, irappa-pattar commented on docs/README.md
> +         "MetricDefinition":{
MetricProperty Should be added in MetricValues.

2021-07-16 09:49 UTC, sunithasomanna commented on docs/README.md
> +         "MetricDefinition":{
Addressed

2021-07-16 09:50 UTC, sunithasomanna commented on docs/README.md
> +              'https://{odimra_host}:{port}/redfish/v1/TelemetryService/MetricDefinitions/'
Retaining this after confirming with Bharath B

2021-07-16 09:51 UTC, irappa-pattar approved these changes
LGTM

2021-07-19 10:47 UTC, shivacharanms approved these changes

2021-07-19 12:04 UTC, bharath-b-hpe approved these changes

2021-07-19 12:04 UTC, merged