Reset system response update
sunithasomanna/ODIM pull request #85
Opened 2022-07-21 13:04 UTC by sunithasomanna

Updated response for reset system in the API readme

2022-07-22 07:03 UTC, jeevan-kamkar reviewed
address the comment

2022-07-22 07:03 UTC, jeevan-kamkar commented on docs/README.md
> -			"MessageId": "Base.1.13.0.Success"
message-id please retain the old one only

2022-07-22 12:09 UTC, sunithasomanna commented on docs/README.md
> -			"MessageId": "Base.1.13.0.Success"
Reverted to "MessageId": "Base.1.11.Success"

2022-07-25 11:43 UTC, jeevan-kamkar requested changes
Address the requested chages

2022-07-25 11:43 UTC, jeevan-kamkar commented on docs/README.md
>     "Drives":[
Drives Should be the property of links please find the sample `"Links":{
"Drives": [
{
"@odata.id": "/redfish/v1/Systems/e99a4606-1939-4942-9bf9-b7b1d5b26758.System.Embedded.1/Storage/RAID.Integrated.1-1/Drives/Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1"
}
]
  }`

2022-07-25 12:01 UTC, sunithasomanna commented on docs/README.md
>     "Drives":[
addressed

2022-07-25 13:03 UTC, jeevan-kamkar approved these changes

2022-07-26 05:53 UTC, shivacharanms approved these changes

2022-07-26 07:49 UTC, amar-shalgar requested changes
Please address changes

2022-07-26 07:49 UTC, amar-shalgar commented on docs/README.md
> +|Links|Object (required)|Links of drives collections.|
This is links to individual drives
Drives is part of Links property please check how this can be shown

2022-07-26 07:49 UTC, amar-shalgar commented on docs/README.md
>  |**Response code** | `200 OK` |
Cross check the response code, its not matching with the returns description

2022-07-27 12:03 UTC, sunithasomanna commented on docs/README.md
> +|Links|Object (required)|Links of drives collections.|
Addressed the comment

2022-07-27 12:03 UTC, sunithasomanna commented on docs/README.md
>  |**Response code** | `200 OK` |
addressed the comment

2022-07-27 12:12 UTC, amar-shalgar requested changes

2022-07-27 12:12 UTC, amar-shalgar commented on docs/README.md
>  |@odata.id }]<br> |String|A link to a drive resource.|
Closing brace of links is missing

2022-07-27 12:24 UTC, sunithasomanna commented on docs/README.md
>  |@odata.id }]<br> |String|A link to a drive resource.|
Added in odata.id. Please review and let me know if it is fine

2022-07-27 12:28 UTC, amar-shalgar approved these changes

2022-07-27 14:09 UTC, shivacharanms approved these changes

2022-07-27 14:12 UTC, merged