Event subscription with aggregates and fabrics sections
sunithasomanna/ODIM pull request #86
Opened 2022-07-22 12:33 UTC by sunithasomanna

Added sections for Event subscription with aggregates and fabrics in the API readme

2022-07-25 11:53 UTC, chauberahul1993 approved these changes

2022-07-26 04:10 UTC, jeevan-kamkar approved these changes

2022-07-26 07:53 UTC, amar-shalgar requested changes

2022-07-26 07:53 UTC, amar-shalgar commented on docs/README.md
> +>**curl command to create event subscriptions for systems**
subscriptions can be created for multiple other things. i feel systems should not be here

2022-07-26 07:53 UTC, amar-shalgar commented on docs/README.md
> +>**Sample request body to create event subscriptions for systems**
subscriptions can be created for multiple other things. i feel systems should not be here

2022-07-26 07:53 UTC, amar-shalgar commented on docs/README.md
> +>**curl command to create event subscriptions for fabrics**
Should we add single subscription request and mention what other OriginResources can be provided

2022-07-28 14:25 UTC, sunithasomanna commented on docs/README.md
> +>**curl command to create event subscriptions for systems**
Addressed comment

2022-07-28 14:26 UTC, sunithasomanna commented on docs/README.md
> +>**Sample request body to create event subscriptions for systems**
Addressed comment

2022-07-28 14:26 UTC, sunithasomanna commented on docs/README.md
> +>**curl command to create event subscriptions for fabrics**
added Aggregates to the table in Origin Resources section

2022-07-29 09:00 UTC, shivacharanms approved these changes

2022-07-29 09:00 UTC, merged